// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: authpb/passwd.proto

//buf:lint:ignore PACKAGE_VERSION_SUFFIX
// Some doc

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthSvc_CreateAuth_FullMethodName      = "/authpb.AuthSvc/CreateAuth"
	AuthSvc_LoginPasswd_FullMethodName     = "/authpb.AuthSvc/LoginPasswd"
	AuthSvc_LoginOauth2_FullMethodName     = "/authpb.AuthSvc/LoginOauth2"
	AuthSvc_ValidateToken_FullMethodName   = "/authpb.AuthSvc/ValidateToken"
	AuthSvc_UpdatePasswd_FullMethodName    = "/authpb.AuthSvc/UpdatePasswd"
	AuthSvc_ListAuth_FullMethodName        = "/authpb.AuthSvc/ListAuth"
	AuthSvc_GetOauth2Config_FullMethodName = "/authpb.AuthSvc/GetOauth2Config"
)

// AuthSvcClient is the client API for AuthSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthSvcClient interface {
	CreateAuth(ctx context.Context, in *CreateAuthRequest, opts ...grpc.CallOption) (*CreateAuthResponse, error)
	LoginPasswd(ctx context.Context, in *LoginPasswdRequest, opts ...grpc.CallOption) (*LoginPasswdResponse, error)
	LoginOauth2(ctx context.Context, in *LoginOauth2Request, opts ...grpc.CallOption) (*LoginOauth2Response, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	UpdatePasswd(ctx context.Context, in *UpdatePasswdRequest, opts ...grpc.CallOption) (*UpdatePasswdResponse, error)
	ListAuth(ctx context.Context, in *ListAuthRequest, opts ...grpc.CallOption) (*ListAuthResponse, error)
	GetOauth2Config(ctx context.Context, in *GetOauth2ConfigRequest, opts ...grpc.CallOption) (*GetOauth2ConfigResponse, error)
}

type authSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthSvcClient(cc grpc.ClientConnInterface) AuthSvcClient {
	return &authSvcClient{cc}
}

func (c *authSvcClient) CreateAuth(ctx context.Context, in *CreateAuthRequest, opts ...grpc.CallOption) (*CreateAuthResponse, error) {
	out := new(CreateAuthResponse)
	err := c.cc.Invoke(ctx, AuthSvc_CreateAuth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSvcClient) LoginPasswd(ctx context.Context, in *LoginPasswdRequest, opts ...grpc.CallOption) (*LoginPasswdResponse, error) {
	out := new(LoginPasswdResponse)
	err := c.cc.Invoke(ctx, AuthSvc_LoginPasswd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSvcClient) LoginOauth2(ctx context.Context, in *LoginOauth2Request, opts ...grpc.CallOption) (*LoginOauth2Response, error) {
	out := new(LoginOauth2Response)
	err := c.cc.Invoke(ctx, AuthSvc_LoginOauth2_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSvcClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AuthSvc_ValidateToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSvcClient) UpdatePasswd(ctx context.Context, in *UpdatePasswdRequest, opts ...grpc.CallOption) (*UpdatePasswdResponse, error) {
	out := new(UpdatePasswdResponse)
	err := c.cc.Invoke(ctx, AuthSvc_UpdatePasswd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSvcClient) ListAuth(ctx context.Context, in *ListAuthRequest, opts ...grpc.CallOption) (*ListAuthResponse, error) {
	out := new(ListAuthResponse)
	err := c.cc.Invoke(ctx, AuthSvc_ListAuth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authSvcClient) GetOauth2Config(ctx context.Context, in *GetOauth2ConfigRequest, opts ...grpc.CallOption) (*GetOauth2ConfigResponse, error) {
	out := new(GetOauth2ConfigResponse)
	err := c.cc.Invoke(ctx, AuthSvc_GetOauth2Config_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthSvcServer is the server API for AuthSvc service.
// All implementations must embed UnimplementedAuthSvcServer
// for forward compatibility
type AuthSvcServer interface {
	CreateAuth(context.Context, *CreateAuthRequest) (*CreateAuthResponse, error)
	LoginPasswd(context.Context, *LoginPasswdRequest) (*LoginPasswdResponse, error)
	LoginOauth2(context.Context, *LoginOauth2Request) (*LoginOauth2Response, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	UpdatePasswd(context.Context, *UpdatePasswdRequest) (*UpdatePasswdResponse, error)
	ListAuth(context.Context, *ListAuthRequest) (*ListAuthResponse, error)
	GetOauth2Config(context.Context, *GetOauth2ConfigRequest) (*GetOauth2ConfigResponse, error)
	mustEmbedUnimplementedAuthSvcServer()
}

// UnimplementedAuthSvcServer must be embedded to have forward compatible implementations.
type UnimplementedAuthSvcServer struct {
}

func (UnimplementedAuthSvcServer) CreateAuth(context.Context, *CreateAuthRequest) (*CreateAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuth not implemented")
}
func (UnimplementedAuthSvcServer) LoginPasswd(context.Context, *LoginPasswdRequest) (*LoginPasswdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginPasswd not implemented")
}
func (UnimplementedAuthSvcServer) LoginOauth2(context.Context, *LoginOauth2Request) (*LoginOauth2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginOauth2 not implemented")
}
func (UnimplementedAuthSvcServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthSvcServer) UpdatePasswd(context.Context, *UpdatePasswdRequest) (*UpdatePasswdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePasswd not implemented")
}
func (UnimplementedAuthSvcServer) ListAuth(context.Context, *ListAuthRequest) (*ListAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAuth not implemented")
}
func (UnimplementedAuthSvcServer) GetOauth2Config(context.Context, *GetOauth2ConfigRequest) (*GetOauth2ConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOauth2Config not implemented")
}
func (UnimplementedAuthSvcServer) mustEmbedUnimplementedAuthSvcServer() {}

// UnsafeAuthSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthSvcServer will
// result in compilation errors.
type UnsafeAuthSvcServer interface {
	mustEmbedUnimplementedAuthSvcServer()
}

func RegisterAuthSvcServer(s grpc.ServiceRegistrar, srv AuthSvcServer) {
	s.RegisterService(&AuthSvc_ServiceDesc, srv)
}

func _AuthSvc_CreateAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).CreateAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSvc_CreateAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).CreateAuth(ctx, req.(*CreateAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSvc_LoginPasswd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPasswdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).LoginPasswd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSvc_LoginPasswd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).LoginPasswd(ctx, req.(*LoginPasswdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSvc_LoginOauth2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginOauth2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).LoginOauth2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSvc_LoginOauth2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).LoginOauth2(ctx, req.(*LoginOauth2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSvc_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSvc_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSvc_UpdatePasswd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).UpdatePasswd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSvc_UpdatePasswd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).UpdatePasswd(ctx, req.(*UpdatePasswdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSvc_ListAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).ListAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSvc_ListAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).ListAuth(ctx, req.(*ListAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthSvc_GetOauth2Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOauth2ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthSvcServer).GetOauth2Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthSvc_GetOauth2Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthSvcServer).GetOauth2Config(ctx, req.(*GetOauth2ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthSvc_ServiceDesc is the grpc.ServiceDesc for AuthSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.AuthSvc",
	HandlerType: (*AuthSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuth",
			Handler:    _AuthSvc_CreateAuth_Handler,
		},
		{
			MethodName: "LoginPasswd",
			Handler:    _AuthSvc_LoginPasswd_Handler,
		},
		{
			MethodName: "LoginOauth2",
			Handler:    _AuthSvc_LoginOauth2_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AuthSvc_ValidateToken_Handler,
		},
		{
			MethodName: "UpdatePasswd",
			Handler:    _AuthSvc_UpdatePasswd_Handler,
		},
		{
			MethodName: "ListAuth",
			Handler:    _AuthSvc_ListAuth_Handler,
		},
		{
			MethodName: "GetOauth2Config",
			Handler:    _AuthSvc_GetOauth2Config_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authpb/passwd.proto",
}
