// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: msgbus/v1/test.proto

// Message bus

package msgbusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deprecated
type TestCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Deprecated: Marked as deprecated in msgbus/v1/test.proto.
	Info string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *TestCommand) Reset() {
	*x = TestCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgbus_v1_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCommand) ProtoMessage() {}

func (x *TestCommand) ProtoReflect() protoreflect.Message {
	mi := &file_msgbus_v1_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCommand.ProtoReflect.Descriptor instead.
func (*TestCommand) Descriptor() ([]byte, []int) {
	return file_msgbus_v1_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Deprecated: Marked as deprecated in msgbus/v1/test.proto.
func (x *TestCommand) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_msgbus_v1_test_proto protoreflect.FileDescriptor

var file_msgbus_v1_test_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x73, 0x67, 0x62, 0x75, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x73, 0x67, 0x62, 0x75, 0x73, 0x2e, 0x76,
	0x31, 0x22, 0x49, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x02, 0x18, 0x01, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x81, 0x01, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x73, 0x67, 0x62, 0x75, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x09,
	0x54, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x20, 0x62, 0x65, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x75,
	0x73, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x75, 0x73, 0x76, 0x31, 0xa2, 0x02, 0x03,
	0x4d, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x4d, 0x73, 0x67, 0x62, 0x75, 0x73, 0x2e, 0x56, 0x31, 0xca,
	0x02, 0x09, 0x4d, 0x73, 0x67, 0x62, 0x75, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x4d, 0x73,
	0x67, 0x62, 0x75, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x4d, 0x73, 0x67, 0x62, 0x75, 0x73, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgbus_v1_test_proto_rawDescOnce sync.Once
	file_msgbus_v1_test_proto_rawDescData = file_msgbus_v1_test_proto_rawDesc
)

func file_msgbus_v1_test_proto_rawDescGZIP() []byte {
	file_msgbus_v1_test_proto_rawDescOnce.Do(func() {
		file_msgbus_v1_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgbus_v1_test_proto_rawDescData)
	})
	return file_msgbus_v1_test_proto_rawDescData
}

var file_msgbus_v1_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msgbus_v1_test_proto_goTypes = []interface{}{
	(*TestCommand)(nil), // 0: msgbus.v1.TestCommand
}
var file_msgbus_v1_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msgbus_v1_test_proto_init() }
func file_msgbus_v1_test_proto_init() {
	if File_msgbus_v1_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgbus_v1_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgbus_v1_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgbus_v1_test_proto_goTypes,
		DependencyIndexes: file_msgbus_v1_test_proto_depIdxs,
		MessageInfos:      file_msgbus_v1_test_proto_msgTypes,
	}.Build()
	File_msgbus_v1_test_proto = out.File
	file_msgbus_v1_test_proto_rawDesc = nil
	file_msgbus_v1_test_proto_goTypes = nil
	file_msgbus_v1_test_proto_depIdxs = nil
}
