// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: be/common/templ/v1/templ.proto

// Template data for render

package templv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonData) Reset() {
	*x = PersonData{}
	mi := &file_be_common_templ_v1_templ_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonData) ProtoMessage() {}

func (x *PersonData) ProtoReflect() protoreflect.Message {
	mi := &file_be_common_templ_v1_templ_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonData.ProtoReflect.Descriptor instead.
func (*PersonData) Descriptor() ([]byte, []int) {
	return file_be_common_templ_v1_templ_proto_rawDescGZIP(), []int{0}
}

func (x *PersonData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersonData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PersonData) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Person        *PersonData                 `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	Items         map[string]*structpb.Struct `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_be_common_templ_v1_templ_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_be_common_templ_v1_templ_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_be_common_templ_v1_templ_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetPerson() *PersonData {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *Data) GetItems() map[string]*structpb.Struct {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_be_common_templ_v1_templ_proto protoreflect.FileDescriptor

var file_be_common_templ_v1_templ_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x62, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb8, 0x01,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x51, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x67, 0x72, 0x72, 0x72, 0x72, 0x2f, 0x62, 0x74,
	0x6d, 0x74, 0x2d, 0x75, 0x69, 0x2f, 0x62, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_be_common_templ_v1_templ_proto_rawDescOnce sync.Once
	file_be_common_templ_v1_templ_proto_rawDescData = file_be_common_templ_v1_templ_proto_rawDesc
)

func file_be_common_templ_v1_templ_proto_rawDescGZIP() []byte {
	file_be_common_templ_v1_templ_proto_rawDescOnce.Do(func() {
		file_be_common_templ_v1_templ_proto_rawDescData = protoimpl.X.CompressGZIP(file_be_common_templ_v1_templ_proto_rawDescData)
	})
	return file_be_common_templ_v1_templ_proto_rawDescData
}

var file_be_common_templ_v1_templ_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_be_common_templ_v1_templ_proto_goTypes = []any{
	(*PersonData)(nil),      // 0: templ.v1.PersonData
	(*Data)(nil),            // 1: templ.v1.Data
	nil,                     // 2: templ.v1.Data.ItemsEntry
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_be_common_templ_v1_templ_proto_depIdxs = []int32{
	0, // 0: templ.v1.Data.person:type_name -> templ.v1.PersonData
	2, // 1: templ.v1.Data.items:type_name -> templ.v1.Data.ItemsEntry
	3, // 2: templ.v1.Data.ItemsEntry.value:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_be_common_templ_v1_templ_proto_init() }
func file_be_common_templ_v1_templ_proto_init() {
	if File_be_common_templ_v1_templ_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_be_common_templ_v1_templ_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_be_common_templ_v1_templ_proto_goTypes,
		DependencyIndexes: file_be_common_templ_v1_templ_proto_depIdxs,
		MessageInfos:      file_be_common_templ_v1_templ_proto_msgTypes,
	}.Build()
	File_be_common_templ_v1_templ_proto = out.File
	file_be_common_templ_v1_templ_proto_rawDesc = nil
	file_be_common_templ_v1_templ_proto_goTypes = nil
	file_be_common_templ_v1_templ_proto_depIdxs = nil
}
