steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-f',
          './ui/web/.deploy/Dockerfile',
        '-t',
        'europe-central2-docker.pkg.dev/bikeareaui/btmt/web:$SHORT_SHA',
        './ui/web']
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
        'europe-central2-docker.pkg.dev/bikeareaui/btmt/web:$SHORT_SHA',
      ]



  # # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'web',
      '--allow-unauthenticated',
      '--ingress',
      'all', 
      '--port',
      '8080',
      '--image=europe-central2-docker.pkg.dev/bikeareaui/btmt/web:$SHORT_SHA',
      '--region',
      'europe-central2',
      '--platform',
      'managed'
      ]
