// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: be/svc-people/peoplepb/v1/people.proto

// Manages people in the system(s)
// People can be clients, users, admins or any person.

package peoplepbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeopleSvc_Update_FullMethodName  = "/peoplepb.v1.PeopleSvc/Update"
	PeopleSvc_Save_FullMethodName    = "/peoplepb.v1.PeopleSvc/Save"
	PeopleSvc_Get_FullMethodName     = "/peoplepb.v1.PeopleSvc/Get"
	PeopleSvc_List_FullMethodName    = "/peoplepb.v1.PeopleSvc/List"
	PeopleSvc_IDParse_FullMethodName = "/peoplepb.v1.PeopleSvc/IDParse"
)

// PeopleSvcClient is the client API for PeopleSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeopleSvcClient interface {
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	IDParse(ctx context.Context, in *IDParseRequest, opts ...grpc.CallOption) (*IDParseResponse, error)
}

type peopleSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewPeopleSvcClient(cc grpc.ClientConnInterface) PeopleSvcClient {
	return &peopleSvcClient{cc}
}

func (c *peopleSvcClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, PeopleSvc_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peopleSvcClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, PeopleSvc_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peopleSvcClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, PeopleSvc_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peopleSvcClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, PeopleSvc_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peopleSvcClient) IDParse(ctx context.Context, in *IDParseRequest, opts ...grpc.CallOption) (*IDParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDParseResponse)
	err := c.cc.Invoke(ctx, PeopleSvc_IDParse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeopleSvcServer is the server API for PeopleSvc service.
// All implementations must embed UnimplementedPeopleSvcServer
// for forward compatibility.
type PeopleSvcServer interface {
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	IDParse(context.Context, *IDParseRequest) (*IDParseResponse, error)
	mustEmbedUnimplementedPeopleSvcServer()
}

// UnimplementedPeopleSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeopleSvcServer struct{}

func (UnimplementedPeopleSvcServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPeopleSvcServer) Save(context.Context, *SaveRequest) (*SaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedPeopleSvcServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPeopleSvcServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPeopleSvcServer) IDParse(context.Context, *IDParseRequest) (*IDParseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IDParse not implemented")
}
func (UnimplementedPeopleSvcServer) mustEmbedUnimplementedPeopleSvcServer() {}
func (UnimplementedPeopleSvcServer) testEmbeddedByValue()                   {}

// UnsafePeopleSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeopleSvcServer will
// result in compilation errors.
type UnsafePeopleSvcServer interface {
	mustEmbedUnimplementedPeopleSvcServer()
}

func RegisterPeopleSvcServer(s grpc.ServiceRegistrar, srv PeopleSvcServer) {
	// If the following call pancis, it indicates UnimplementedPeopleSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeopleSvc_ServiceDesc, srv)
}

func _PeopleSvc_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeopleSvcServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeopleSvc_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeopleSvcServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeopleSvc_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeopleSvcServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeopleSvc_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeopleSvcServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeopleSvc_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeopleSvcServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeopleSvc_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeopleSvcServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeopleSvc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeopleSvcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeopleSvc_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeopleSvcServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeopleSvc_IDParse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeopleSvcServer).IDParse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeopleSvc_IDParse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeopleSvcServer).IDParse(ctx, req.(*IDParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeopleSvc_ServiceDesc is the grpc.ServiceDesc for PeopleSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeopleSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peoplepb.v1.PeopleSvc",
	HandlerType: (*PeopleSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _PeopleSvc_Update_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _PeopleSvc_Save_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PeopleSvc_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PeopleSvc_List_Handler,
		},
		{
			MethodName: "IDParse",
			Handler:    _PeopleSvc_IDParse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "be/svc-people/peoplepb/v1/people.proto",
}
